function isSafetyLabel(x){return String(x||"").normalize("NFKC").replace(/[\u200B-\u200D\u2060\uFEFF]/g,"").replace(/[^A-Za-z]/g,"").toUpperCase()==="SAFETY"}
const STORAGE_KEY="thinkstill_v38_4_3_seen",SAVED_KEY="thinkstill_v38_4_3_saved",THEME_KEY="thinkstill_v38_4_3_theme";let rituals=[],currentRitual=null,currentInput="",round=1;const $=id=>document.getElementById(id);
function esc(s=""){return String(s).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));}
function norm(s=""){return String(s).toLowerCase().normalize("NFKD").replace(/[^a-z0-9\s'-]/g," ").replace(/\s+/g," ").trim();}
const STOP=new Set("a an the and or but if then to of in on at for from with without into is are was were be been being i me my mine we our you your it this that these those as so very really just still feel feels feeling think thinking thought thoughts mind right now about".split(" "));
function tokens(s){return norm(s).split(" ").filter(w=>w.length>2&&!STOP.has(w));}
function getSet(k){try{return new Set(JSON.parse(localStorage.getItem(k)||"[]"));}catch{return new Set();}}
function saveSet(k,s){localStorage.setItem(k,JSON.stringify([...s]));}
function seenIds(){return getSet(STORAGE_KEY)}function markSeen(id){const s=seenIds();s.add(id);saveSet(STORAGE_KEY,s)}
function pool(){let s=seenIds();if(s.size>=rituals.length){localStorage.removeItem(STORAGE_KEY);s=new Set()}return rituals.filter(r=>!s.has(r.id));}
function fieldScore(q,field,w){const f=norm(field||"");let total=0;for(const word of q){if(f.includes(word))total+=w;if(word.length>5&&f.split(" ").some(x=>x.startsWith(word.slice(0,5))))total+=w*.3}return total}
function score(r,input){const q=tokens(input);if(!q.length)return 0;const rt=r.routing||{};let total=0;total+=fieldScore(q,rt.trigger,8);total+=fieldScore(q,rt.secondaryTrigger,5);total+=fieldScore(q,rt.pattern,9);total+=fieldScore(q,rt.distressCue,3);total+=fieldScore(q,r.goal,3);total+=fieldScore(q,r.title,1.5);total+=fieldScore(q,r.steps,1);const tw=Math.max(.2,Number(rt.triggerWeight||1)),pw=Math.max(.2,Number(rt.patternWeight||1));return total*(.82+.1*Math.log1p(tw)+.08*Math.log1p(pw))+Math.random()*.02}
function choose(input=""){const p=pool();if(!p.length)return rituals[Math.floor(Math.random()*rituals.length)];if(!input.trim())return p[Math.floor(Math.random()*p.length)];const ranked=p.map(r=>[score(r,input),r]).sort((a,b)=>b[0]-a[0]);const best=ranked[0][0];if(best<=0)return p[Math.floor(Math.random()*p.length)];const close=ranked.filter(([s])=>s>=best*.9).slice(0,5);return close[Math.floor(Math.random()*close.length)][1]}
function parseStep(line){return line.replace(/^\s*\d+[.)]\s*/,"").trim()}function formatStep(line){const p=line.split(/\s+[—–-]\s+/,2);return p.length===2?`<strong>${esc(p[0])}</strong> — ${esc(p[1])}`:esc(line)}
function fullText(r){return [r.title,`PLAY TIME\n${r.playTime}`,`GOAL\n${r.goal}`,r.steps,`WIN\n${r.win}`,r.supports,`FORMULA FLOW\n${r.formulaFlow}`,String(r.safety||"").split(/\r?\n/).filter(x=>!isSafetyLabel(x)).join("\n")].filter(Boolean).join("\n\n")}

function resetFeedback(){$("feedbackButtons").hidden=false;$("refinePanel").hidden=true;$("helpedPanel").hidden=true;$("roundHint").textContent=round>=3?"Three rounds and still no fit? Reword what is happening now, or take a break before trying again.":""}
function retryWithCue(cue=""){const base=currentInput.trim();const q=cue?`${base}. ${cue}`:base;round=Math.min(9,round+1);render(choose(q));}
function showRefine(){$("feedbackButtons").hidden=true;$("refinePanel").hidden=false;$("helpedPanel").hidden=true;$("roundHint").textContent=round>=3?"Three rounds and still no fit? Reword what is happening now, or take a break before trying again.":""}
function showHelped(){$("feedbackButtons").hidden=true;$("refinePanel").hidden=true;$("helpedPanel").hidden=false}
function render(r){currentRitual=r;markSeen(r.id);$("missionText").textContent=currentInput||"Open exploration";$("roundPill").textContent=`ROUND ${round}`;$("feedbackRound").textContent=`ROUND ${round}`;resetFeedback();$("welcome").hidden=true;$("ritualScreen").hidden=false;$("bubblePill").textContent=`◇ ${r.bubble} BUBBLE`;$("timePill").textContent=r.playTime||"about 1 minute";$("ritualTitle").textContent=r.title||r.name||"Mind Reset";$("ritualGoal").textContent=r.goal||"";const steps=(Array.isArray(r.stepsArray)&&r.stepsArray.length?r.stepsArray:String(r.steps||"").split(/\r?\n/)).map(x=>String(x).trim()).filter(Boolean);$("stepsList").innerHTML=steps.map(x=>`<li>${formatStep(parseStep(x))}</li>`).join("");$("ritualWin").textContent=String(r.win||r.winReward||"").replace(/^\s*✓\s*/,"✓ ");const supports=(Array.isArray(r.supportsArray)&&r.supportsArray.length?r.supportsArray:String(r.supports||"").split(/\r?\n/).map(x=>x.replace(/^\s*[•*-]\s*/,""))).map(x=>String(x).trim()).filter(Boolean).slice(0,5);$("supportsList").innerHTML=supports.map(x=>`<li>${esc(x)}</li>`).join("");const flow=String(r.formulaFlow||"").split("→").map(x=>x.trim()).filter(Boolean);$("flow").innerHTML=flow.map((x,i)=>`${i?'<span class="flow-arrow">→</span>':''}<span class="flow-chip">${esc(x)}</span>`).join("");const safetyLines=String(r.safety||"").split(/\r?\n/).map(x=>x.trim()).filter(x=>x&&!isSafetyLabel(x));$("safety").innerHTML=safetyLines.map((x,i)=>`<span class="${i===0&&/^PAUSE$/i.test(x)?'pause':'safety-line'}">${esc(x)}</span>`).join("");$("progressText").textContent=`${seenIds().size} of ${rituals.length} rituals used before the pool resets.`;$("saveBtn").textContent=getSet(SAVED_KEY).has(r.id)?"Saved ✓":"Save";requestAnimationFrame(()=>window.scrollTo({top:0,behavior:"smooth"}))}
function showFromInput(){currentInput=$("thoughtInput").value.trim();round=1;render(choose(currentInput))}
function setTheme(t){document.documentElement.dataset.theme=t;localStorage.setItem(THEME_KEY,t);$("themeToggle").textContent=t==="light"?"☀ Bright":"☾ Dark"}
async function copyCurrent(){if(!currentRitual)return;try{await navigator.clipboard.writeText(fullText(currentRitual));$("copyBtn").textContent="Copied ✓";setTimeout(()=>$("copyBtn").textContent="Copy",1200)}catch{$("copyBtn").textContent="Copy failed"}}
function toggleSave(){if(!currentRitual)return;const s=getSet(SAVED_KEY);if(s.has(currentRitual.id))s.delete(currentRitual.id);else s.add(currentRitual.id);saveSet(SAVED_KEY,s);$("saveBtn").textContent=s.has(currentRitual.id)?"Saved ✓":"Save"}
function resetToInput(){round=1;$("ritualScreen").hidden=true;$("welcome").hidden=false;$("thoughtInput").focus();window.scrollTo({top:0,behavior:"smooth"})}
async function init(){setTheme(localStorage.getItem(THEME_KEY)||"dark");try{const res=await fetch("rituals.json",{cache:"no-store"});if(!res.ok)throw new Error(`HTTP ${res.status}`);rituals=await res.json();if(!Array.isArray(rituals)||rituals.length!==400)throw new Error("Expected exactly 400 rituals.")}catch(err){$("welcome").innerHTML=`<p class="eyebrow">RITUAL DATA ERROR</p><h1>rituals.json did not load.</h1><p>${esc(err.message||String(err))}</p>`;return}$("sendBtn").onclick=showFromInput;$("randomBtn").onclick=()=>{currentInput="";round=1;render(choose(""))};$("thoughtInput").addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();showFromInput()}});$("anotherBtn").onclick=()=>retryWithCue();$("changeBtn").onclick=resetToInput;$("closeBtn").onclick=resetToInput;$("themeToggle").onclick=()=>setTheme(document.documentElement.dataset.theme==="light"?"dark":"light");$("copyBtn").onclick=copyCurrent;$("saveBtn").onclick=toggleSave;$("helpedBtn").onclick=showHelped;$("refineBtn").onclick=showRefine;$("notYetBtn").onclick=showRefine;$("retryBtn").onclick=()=>retryWithCue();$("newQuestBtn").onclick=resetToInput;document.querySelectorAll("[data-cue]").forEach(b=>b.addEventListener("click",()=>retryWithCue(b.dataset.cue||"")))}
document.addEventListener("DOMContentLoaded",init);