/* Build the Framer code component: ThinkStillReflect.tsx with the whole Reflect bundle embedded, so the component works
 * with no other files. Bubble art loads from Asset Base URL (the shared bubble-expressions folder). Invites need the
 * Reflect room server URL (the Cloudflare Worker in games/reflect/src/server/worker.ts). */
const fs = require('fs');
const path = require('path');

function tsx(js, ref) {
  return `// @ts-nocheck
/*
 * ThinkStill Reflect — Framer code component.
 * Multiplayer reflection rituals: Group Think Glitch (pilot 1). Solo play works anywhere with labelled Bubble
 * companions; inviting friends needs Room Server (the Reflect Cloudflare Worker, wss://…).
 * Generated by games/reflect/tools/build-reflect.js${ref ? ' at ' + ref : ''}. Edit the TypeScript source, not this file.
 * Shares ThinkStill keys: theme (__ts_chat_theme_v181) and Reset's shared media (__ts_reset_shared_media_v1).
 */
import * as React from "react"
import { addPropertyControls, ControlType, RenderTarget } from "framer"

const ASSET_BASE = "https://raw.githubusercontent.com/ramkumarjothi1982/thinkstill-rituals/main/bubble-expressions/"
const BUNDLE = ${JSON.stringify(js)}

function api() {
    const g = globalThis as any
    if (!g.ThinkStillReflect) new Function(BUNDLE)()
    return g.ThinkStillReflect
}
function isStatic() {
    try {
        const t = RenderTarget.current()
        return t === RenderTarget.canvas || t === RenderTarget.thumbnail || t === RenderTarget.export
    } catch (e) {
        return false
    }
}
const clean = (v) => (typeof v === "string" ? v.trim() : "")
function roomFromUrl() {
    try {
        const q = new URLSearchParams(window.location.search).get("reflectRoom")
        return q && /^[A-Z2-9]{5}$/.test(q) ? q : undefined
    } catch (e) {
        return undefined
    }
}

/**
 * ThinkStill Reflect
 *
 * @framerIntrinsicWidth 390
 * @framerIntrinsicHeight 844
 * @framerSupportedLayoutWidth any-prefer-fixed
 * @framerSupportedLayoutHeight any-prefer-fixed
 */
export default function ThinkStillReflect(props) {
    const hostRef = React.useRef(null)
    const propsRef = React.useRef(props)
    propsRef.current = props
    const still = isStatic()
    const key = [clean(props.roomServer), clean(props.assetBase), props.theme, props.soundOn, props.motion, still].join("|")
    React.useEffect(() => {
        const host = hostRef.current
        if (!host || still) return
        const p = propsRef.current
        const el = document.createElement("div")
        el.style.cssText = "position:absolute;inset:0"
        host.appendChild(el)
        let m = null
        try {
            m = api().mount(el, {
                roomServer: clean(p.roomServer) || undefined,
                assetBase: clean(p.assetBase) || ASSET_BASE,
                theme: p.theme || "system",
                sound: p.soundOn !== false,
                reducedMotion: p.motion === "reduced" ? "on" : p.motion === "full" ? "off" : "system",
                room: roomFromUrl(),
                onExit: typeof p.onExit === "function" ? () => propsRef.current.onExit && propsRef.current.onExit() : undefined,
                onComplete: (info) => propsRef.current.onComplete && propsRef.current.onComplete(info),
            })
        } catch (e) {
            el.textContent = "Reflect could not start: " + (e && e.message ? e.message : e)
        }
        return () => {
            try { m && m.destroy() } catch (e) {}
            el.remove()
        }
    }, [key])
    return (
        <div ref={hostRef} style={{ position: "relative", width: "100%", height: "100%", overflow: "hidden", borderRadius: props.radius || 0, background: "#0f0d1f", ...props.style }}>
            {still ? (
                <div style={{ position: "absolute", inset: 0, display: "grid", placeItems: "center", background: "radial-gradient(120% 90% at 50% 0%, #2a2350, #0f0d1f)", color: "#f5f1ff", fontFamily: "Fredoka, system-ui, sans-serif", textAlign: "center", padding: 24 }}>
                    <div>
                        <div style={{ fontSize: 40, fontWeight: 800 }}>Reflect</div>
                        <div style={{ opacity: 0.75, marginTop: 6 }}>Group Think Glitch · live in preview</div>
                    </div>
                </div>
            ) : null}
        </div>
    )
}

addPropertyControls(ThinkStillReflect, {
    roomServer: { type: ControlType.String, title: "Room Server", placeholder: "wss://reflect-rooms.<you>.workers.dev", defaultValue: "" },
    assetBase: { type: ControlType.String, title: "Asset Base", placeholder: ASSET_BASE, defaultValue: "" },
    theme: { type: ControlType.Enum, title: "Theme", options: ["system", "dark", "bright"], optionTitles: ["System", "Dark", "Bright"], defaultValue: "system" },
    soundOn: { type: ControlType.Boolean, title: "Sound", defaultValue: true },
    motion: { type: ControlType.Enum, title: "Motion", options: ["system", "full", "reduced"], optionTitles: ["System", "Full", "Reduced"], defaultValue: "system" },
    radius: { type: ControlType.Number, title: "Radius", min: 0, max: 48, defaultValue: 0 },
    onExit: { type: ControlType.EventHandler },
    onComplete: { type: ControlType.EventHandler },
})
`;
}

function build(js, DIST, args) {
  const ri = args.indexOf('--ref');
  const ref = ri >= 0 ? args[ri + 1] : '';
  const out = path.join(DIST, 'framer');
  fs.mkdirSync(out, { recursive: true });
  const code = tsx(js, ref);
  fs.writeFileSync(path.join(out, 'ThinkStillReflect.tsx'), code);
  console.log('framer: ThinkStillReflect.tsx', (Buffer.byteLength(code) / 1024).toFixed(1), 'KB');
}
module.exports = { build, tsx };
