export const meta = {
  name: 'thinkstill-founder-gap-audit',
  description: 'Turn the founder master requirements into verifiable acceptance criteria and audit the current Release implementation against them (verified / untested / partial / missing / regression / superseded), with a prioritised fix plan',
  phases: [
    { title: 'Criteria', detail: 'numbered, testable acceptance criteria from FOUNDER_REQUIREMENTS.md' },
    { title: 'Verify', detail: '4 evidence-based verification slices on the integrated build vs the founder-approved baseline' },
    { title: 'Report', detail: 'gap audit + prioritised fix plan' },
  ],
}
const ROOT = '/home/user/thinkstill-rituals/framer'
const FD = ROOT + '/docs/founder'
const GIT = `Git: branch claude/jolly-hopper-ognrxj in /home/user/thinkstill-rituals. Another workflow (release v2) commits in parallel: git add ONLY your exact paths (never -A), on index.lock wait and retry, message ends with exactly:\nCo-Authored-By: Claude Opus 5.5 <noreply@anthropic.com>\nClaude-Session: https://claude.ai/code/session_01SaGZSxDbxtpggsq88ET1Ri\nthen git push -u origin claude/jolly-hopper-ognrxj (on rejection pull --rebase then push). No PRs, no model names.`
const CTX = `READ-ONLY AUDIT (never edit src/, never run framer/build.py without --dev-dir, never commit anything except the files named in your task). Founder requirements: ${FD}/FOUNDER_REQUIREMENTS.md (binding; latest founder instruction wins). Code: ${ROOT}/src/00_arcade.jsx (22.8k lines; grep, then Read offset/limit; the FOUNDER-APPROVED BASELINE is this file as of git commit 485500c: git show 485500c:framer/src/00_arcade.jsx), ${ROOT}/src/eos/*.jsx (new Emotional OS modules, integrated via ${ROOT}/dev/eos_integrate.py groups I1-I3), ${ROOT}/src/99_pixar.jsx, pilot in ${ROOT}/src/pilot/ (not in the release). Builds for evidence (scratch, never the repo): INTEGRATED = python3 ${ROOT}/dev/eos_integrate.py --dev-dir /tmp/ga_int_<you> --modules <all src/eos/*.jsx names>; BASELINE = python3 ${ROOT}/build.py --dev-dir /tmp/ga_base_<you> --modules 00_eos_core.jsx (arcade + Pixar, no EOS integration). Drive with ${ROOT}/dev/drive.mjs launch({dir,width,height}) and ${ROOT}/dev/eos_drive.mjs (startGameById, finishGame, readProgress, runCheckin...). Existing evidence: ${ROOT}/docs/QUALITY_REPORT.md, ${ROOT}/docs/quality/metrics.json + batch_*.json, contact sheets ${ROOT}/dev/shots/quality/sheets/<id>.png (baseline captures), catalog ${ROOT}/docs/catalog_A.md / catalog_B.md, EOS spec ${ROOT}/docs/EOS_SPEC.md (grep only). Tile screenshots with python3 ${ROOT}/dev/contact_sheet.py and Read the sheet. Test at 390x844 first, then 1280x860. Inspect the implementation before declaring anything absent. Honesty: headless Chromium has no audio output and no GPU — sound can only be verified as "scheduled/triggered", performance only relatively; say so. Another workflow is using the CPU: keep browser runs lean (<= 25 games per sweep). Budget <= 90 tool calls, <= 10 image views. Ignore agent-proxy noise.`
const STATUS = `STATUS VALUES: VERIFIED (evidence from running it or exact code proof), IMPLEMENTED-UNTESTED, PARTIAL, MISSING, REGRESSION (worked/was approved in the baseline, broken or changed now — incl. anything the EOS modules altered in an approved finale/burst), SUPERSEDED (older instruction replaced by a newer founder decision — cite both).`
const ROW = { type: 'object', properties: { id: { type: 'string' }, requirement: { type: 'string' }, status: { type: 'string', enum: ['VERIFIED', 'IMPLEMENTED-UNTESTED', 'PARTIAL', 'MISSING', 'REGRESSION', 'SUPERSEDED'] }, scope: { type: 'string', description: 'shared component or game id/name' }, evidence: { type: 'string' }, current: { type: 'string' }, required: { type: 'string' }, severity: { type: 'string', enum: ['P0', 'P1', 'P2', 'P3'] }, fix: { type: 'string' }, fix_location: { type: 'string', enum: ['shared', 'game', 'both', 'n/a'] }, test: { type: 'string' } }, required: ['id', 'requirement', 'status', 'scope', 'evidence', 'severity', 'fix', 'fix_location', 'test'] }
const ROWS = { type: 'object', properties: { rows: { type: 'array', items: ROW } }, required: ['rows'] }

phase('Criteria')
await agent(`${CTX}\n\nCRITERIA. Convert ${FD}/FOUNDER_REQUIREMENTS.md into a numbered list of atomic, verifiable acceptance criteria: id (e.g. P5.4-a), the requirement in one line, the exact pass/fail test (what to run/look at, at which sizes, which games), scope (shared component vs specific games), and conflicts/supersessions with other parts or with docs/CREATIVE_STANDARDS.md / EOS_SPEC owner decisions (e.g. text below image INSIDE the bubble; approved dopamine bursts frozen vs the EOS colour script / flip-word bloom / lighter reveal overlay; the EOS emotion check-in vs the established prompt "What emotion are you carrying?"; 15+1 selector vs expanded catalogue). Group by: A console/layout/header/feedback/controls (Parts 3,10,14), B input/personalisation/upload (4,6), C bubbles/characters (5,7), D gameplay/navigation/arc (8,9,16), E finales/sound/performance (11,12,15), F game-specific corrections (13.1-13.31), G vibes/safety/sharing/architecture (17-20), H process/approval (22-24). Write ${FD}/ACCEPTANCE_CRITERIA.md and commit only that file. ${GIT} Return the list of criterion ids per group.`, { label: 'criteria', phase: 'Criteria' })

phase('Verify')
const SLICES = [
  { key: 'console-input', text: `Groups A, B, G (+ navigation parts of D: Part 9 selector incl. Let ThinkStill choose, manual pick, mid-game switching with no leftover audio/animation, end-of-game Again / New thought / Try <game>, previous/next/Try next game). Check the input prompt wording, the EOS check-in vs the established prompt, mic, the + upload popup (6 slots, position, closing rules), image distribution for 1-6 uploads (generate 6 small test PNGs and upload them via the file input), the "UPLOADED IMAGE" label, header layout (centred title, progress before sound, progress never disappearing), the bottom-right feedback bubble, one-screen mobile layout, Change Vibe / vibes (Jolly, Cheeky, Unfiltered) influence, Vault/save, share (opt-in, no private text), safety screening, music source (Reset per-Bubble URLs vs anything else — grep useSharedMusic and URLs), idle animations.` },
  { key: 'bubbles-characters', text: `Groups C and Part 14. Write ONE DOM probe run over every multi-bubble / image game in the INTEGRATED build at 390x844 and 1280x860 (and the same probe on the BASELINE for comparison): for each visible bubble/object containing a character or uploaded image: is it a true circle (width==height, border-radius >= 50%), is the image fully visible (object-fit contain or equivalent; no important crop), any black/dark mask or box behind image or text (computed background rgba alpha > 0.35 with luminance < 0.15 on the image/text containers), is the user text BELOW the image and INSIDE the same bubble, any image/text overlap, text overflow outside the circle, text size, count of visible bubbles (>= 5 where the multi-bubble system is used), duplicate/incorrect expressions, characters too small. Use a 1-image and a 6-image upload case on a sample of 10 games and no-upload on all. Produce per-game results.` },
  { key: 'game-specific', text: `Group F: every item in Part 13 (13.1-13.31): POP, CLEANSE, CRUSH, RAIN OUT (6th pull -> rain AND visual washout; text + uploaded images fully removed; clouds stay; completion), X-RAY (Kill/Burn All button after reveal, How-to-play), SCRATCH REVEAL (tool, scratch marks follow pointer, real progress, no bottom container, white text), JUGGLE (central straight line, selected rises, 3 clicks wins, How-to-play text exact), KEEP/DROP (bubble between Up/Down, image changes with choice), VOLUME KNOB, GO WEIRD, SPACE MAKER, COIN FLIP, DOOR A/B, KNOB, FACT/STORY/UNSURE, VACUUM (one column, all words visible, "Vacuum suck" button, visible suction), SHRED (paper enters the shredder opening, convincing art), LOWER PLATFORM / SINKING PLATFORM (down arrows, Activate tool, visible downward movement), HOT POTATO (red->blue, bubble pictures inside potatoes, circular full image, larger, user text below image, no HOT label, no black masks), UNHOOK (one large hook, three strings, each disconnect visible), MELT vs BURN distinct, SLINGSHOT (drag tension release travel), BURN, FLUSH, SWIPE AWAY (direction/force), STOMP/CRACK/ZAP/TAP OUT/BIN distinct mechanics, DRAMA MACHINE, ECHO CHAMBER (no overflow), MAGIC TRAPDOOR, PRIORITY BLOCKS / SCALE DOWN / TRADE MACHINE / CONTROL PANEL, UNFOLLOW (stuck at 17% on phone). For each: inspect the code branch AND play it in the INTEGRATED build (phone first); compare to BASELINE when something looks changed.` },
  { key: 'finales-perf', text: `Group E and Part 16: (1) Did any EOS module change an APPROVED dopamine burst or finale? Compare BASELINE vs INTEGRATED for 12 representative games (incl. POP, BURN, SHRED, CLEANSE, RAIN OUT, HOT POTATO, SLINGSHOT, UNHOOK, 100-110 new-wrapper games): capture the finale sequence as 6 frames each at 390x844 in both builds and compare; check specifically the EOS mood colour script + flip-word bloom (any letters over the main burst?), the dots module's lighter .releaseCompleteOverlay, the readability floor, arrows overlays during the burst, any black screen. (2) Lag: frame-time p95/max during bursts in both builds (relative). (3) Progress indicator disappearing, black screens after input, rain audio without washout, switching games leaves audio/rAF/timers running (count active AudioContext nodes / intervals if instrumentable), memory growth over 5 consecutive games. (4) Sound: what is triggered on which action (instrument the sfx/eosTone calls) — scheduling evidence only. (5) Emotional arc: opening / interaction / escalation / twist / finale / completion present? sample 10 games.` },
]
const results = await parallel(SLICES.map(s => () => agent(`${CTX}\n\nVERIFY slice "${s.key}". First read ${FD}/ACCEPTANCE_CRITERIA.md and use its criterion ids. ${STATUS}\nScope: ${s.text}\nFor every criterion in your scope return one row (status + concrete evidence: command/run result, file:line, screenshot path). Write your rows also to ${FD}/verify_${s.key}.json (do not commit).`, { label: `verify:${s.key}`, phase: 'Verify', schema: ROWS })))
const rows = results.filter(Boolean).flatMap(r => r.rows)
log(`Verified ${rows.length} criteria rows from ${results.filter(Boolean).length}/${SLICES.length} slices`)

phase('Report')
const rep = await agent(`${CTX}\n\nREPORT. Merge the verification rows in ${FD}/verify_*.json (${rows.length} rows) into ${FD}/GAP_AUDIT.md for the founder — concise and evidence-based:\n1. Summary table: counts per status (VERIFIED / IMPLEMENTED-UNTESTED / PARTIAL / MISSING / REGRESSION / SUPERSEDED) overall and per group A-H.\n2. CONFIRMED REGRESSIONS first (anything the new work changed in approved behaviour, especially dopamine bursts/finales), each with evidence and the fix.\n3. P0 (broken/blocked: freezes, stalls, missing endings, lost controls), then P1 (global founder rules: black masks, text below image inside bubble, circles, image cropping, upload popup/distribution/label, header/progress, feedback bubble, one-screen mobile, music from Reset, navigation), then P2/P3. For each gap: affected game or shared component, current behaviour, required behaviour, severity, proposed correction, shared vs game, how it will be tested.\n4. Superseded instructions with the newer decision cited.\n5. FIX PLAN: ordered batches — what can be fixed once in shared code to repair many games, what is game-specific — and which items must wait for founder approval (any change to an approved finale/burst).\nAlso write ${FD}/gap_rows.json (all rows). Commit GAP_AUDIT.md, ACCEPTANCE_CRITERIA.md (if changed), gap_rows.json and verify_*.json. ${GIT} Return a 20-line summary for the founder with the counts and the top regressions and P0s.`, { label: 'report', phase: 'Report' })
return { rows: rows.length, rep }
