export const meta = {
  name: 'thinkstill-launch-30',
  description: 'Pick the 30 best ThinkStill games for launch (evidence ranking + creative judgement, emotion coverage, no look-alikes, reliable on phone), restrict the app to them with one reversible launch list, verify all 30 play to the end, and build the single Framer file under 1 MB',
  phases: [
    { title: 'Rank', detail: 'evidence ranker + creative director score all 114 games independently' },
    { title: 'Select', detail: 'merge, enforce coverage and distinctness, write LAUNCH_30.md' },
    { title: 'Build', detail: 'launch list in shared code, every emotion serves only the 30, play all 30 at 390 + 1280, single Framer file' },
  ],
}

const ROOT = '/home/user/thinkstill-rituals/framer'
const DOCS = ROOT + '/docs'
const GIT = `Git: branch claude/jolly-hopper-ognrxj in /home/user/thinkstill-rituals. git add ONLY the exact paths you changed (never -A/-u/.), message ends with exactly:\nCo-Authored-By: Claude Opus 5.5 <noreply@anthropic.com>\nClaude-Session: https://claude.ai/code/session_01SaGZSxDbxtpggsq88ET1Ri\nthen git push -u origin claude/jolly-hopper-ognrxj (retry network errors 4x with 2/4/8/16 s). No PRs, no model names anywhere.`
const CTX = `PROJECT: ThinkStill Release Console — a Framer code component of 114 emotional-release mini-games (110 originals in src/00_arcade.jsx — 23k lines, NEVER read whole: grep then Read offset/limit — plus 111 BIG SIGH, 112 COOL THE VOLCANO, 113 GROUND CONTROL, 114 SKY LANTERNS in src/eos/21-24; shared Emotional OS modules in src/eos/*.jsx: 45 router (emotion -> game routing), 46 pick (ThinkStill picks, no user menu, no-repeat rotation), 30 arrows, 16 bubble faces, 26 ZAP real zapper, 25 CRACK/STOMP real tools = UNFINISHED work in progress).
FOUNDER GOAL NOW: launch with ONLY the 30 best games — "must be viral, addictive, hypnotic, fun, engaging, giving the user instant relief". Addictive means healthily compelling (they come back because it felt good), never pressure mechanics.
EVIDENCE (use it, do not re-test everything): ${DOCS}/QUALITY_REPORT.md (110-game audit: per-game scores, §5 look-alike clusters — 92 games in 11 clusters, §7 routing positions, character audit, pilot rationale), ${DOCS}/quality/metrics.json + ${DOCS}/quality/batch_*.json (rater scores per game id), ${DOCS}/catalog_A.md + ${DOCS}/catalog_B.md (what each game is), ${DOCS}/founder/GAP_AUDIT.md + gap_rows.json (open founder issues per game), ${DOCS}/founder/FEEDBACK_LOG.md (founder feedback; F1 UNHOOK fixed, F4 ZAP fixed with a real zapper, F5 CRACK spanner unfinished, F6 arrows fixed), ${DOCS}/eos_status/v2_unstick-*.done.md (24 stalling games fixed), ${DOCS}/SHIP_NOW_SMOKE.txt, contact sheets ${ROOT}/dev/shots/quality/sheets/<id>.png (if present; tile-viewing is expensive — at most 12 image views per agent).
Budget: <= 80 tool calls per agent unless stated. Ignore "agent-proxy connect_rejected" noise.`

const RANK = {
  type: 'object',
  properties: {
    games: { type: 'array', items: { type: 'object', properties: {
      id: { type: 'number' }, name: { type: 'string' }, score: { type: 'number' },
      emotions: { type: 'array', items: { type: 'string' } }, cluster: { type: 'string' },
      reliable: { type: 'boolean' }, why: { type: 'string' } }, required: ['id', 'name', 'score', 'why'] } },
  },
  required: ['games'],
}

phase('Rank')
const [evidence, creative] = await parallel([
  () => agent(`${CTX}\n\nEVIDENCE RANKER. Score ALL 114 games 0-100 for launch readiness from the evidence: rater quality scores (weight high), completes reliably on a phone (unstick results, smoke runs, known stalls — a game that can freeze must score low), open founder issues (P0/P1 rows lower the score), character/finale quality notes, how often routing serves it (the most-routed games matter most). Record each game's emotions (from the router tables in src/eos/45_eos_router.jsx and the catalog), its look-alike cluster (QUALITY_REPORT §5, or "unique"), reliable yes/no. Return all 114.`, { label: 'rank:evidence', phase: 'Rank', schema: RANK }),
  () => agent(`${CTX}\n\nCREATIVE DIRECTOR (elite mobile game designer + behavioural product designer). Score ALL 114 games 0-100 on what the founder asked: viral (a moment people would screen-record and share), hypnotic (absorbing flowing rhythm), fun and satisfying in the hands (physical game feel, not tap-to-advance), instant relief (a stressed person feels lighter within 60 s), distinct (not a re-skin of another game). Read the catalog rows and the quality notes for each game; view contact sheets only for up to 12 borderline cases. Be decisive and specific in "why" (one line). Record emotions and look-alike cluster. Return all 114.`, { label: 'rank:creative', phase: 'Rank', schema: RANK }),
])
if (!evidence || !creative) throw new Error('a ranking agent returned nothing (usage limit / restart) - resume later')

phase('Select')
const PICK = { type: 'object', properties: { ids: { type: 'array', items: { type: 'number' } }, summary: { type: 'string' } }, required: ['ids', 'summary'] }
const pick = await agent(`${CTX}\n\nLAUNCH SELECTOR. Two independent rankings of all 114 games are below (evidence = launch readiness, creative = viral/hypnotic/fun/relief). Choose EXACTLY 30 launch games:\n- combine both (a game must be reliable on a phone AND strong creatively; a game that can freeze is out);\n- cover every emotion the router serves (read src/eos/45_eos_router.jsx emotion keys, e.g. panic, anger, anxiety, sad, lonely, numb, shame, overthinking, jealousy, good) with at least 3 games each where possible, and enough variety per emotion for the no-repeat rotation;\n- distinct: at most 2 games from any look-alike cluster, and never two games that play the same way;\n- prefer the most-routed games and the founder's showcase fixes (ZAP real zapper, UNHOOK) when strong; include 111-114 unless the evidence says otherwise; CRACK (3) and STOMP (4) have unfinished tool work — include only if their classic version is strong;\n- mix of intensities (big cathartic smash vs. slow hypnotic calm).\nWrite ${DOCS}/LAUNCH_30.md for the founder (plain language): the 30 as a table (id | name | emotions | why it's in — what makes it viral / hypnotic / relieving), emotion coverage table (emotion -> launch games), and the 84 not chosen with a one-line reason each (kept in the code, switched off). Commit it. ${GIT}\nReturn ids (exactly 30) and a 10-line summary.\n\nEVIDENCE RANKING:\n${JSON.stringify(evidence.games).slice(0, 30000)}\n\nCREATIVE RANKING:\n${JSON.stringify(creative.games).slice(0, 30000)}`, { label: 'select:30', phase: 'Select', schema: PICK })
if (!pick || !pick.ids || pick.ids.length !== 30) throw new Error('selection did not return exactly 30 ids - resume later')
log(`Launch 30: ${pick.ids.join(', ')}`)

phase('Build')
const build = await agent(`${CTX}\n\nLAUNCH BUILDER. The founder's 30 launch games (ids): ${JSON.stringify(pick.ids)} (details in ${DOCS}/LAUNCH_30.md).\n1. Add ONE reversible launch list in shared code (e.g. const EOS_LAUNCH_IDS = new Set([...]) in src/eos/00_eos_core.jsx or 45_eos_router.jsx) and apply it at every choke point so users can ONLY ever get these 30: the emotion router (45; when a route's first choice is excluded, fall through to the next launch game for that emotion — never to an excluded game), the ThinkStill pick + no-repeat rotation (46; groups contain only launch games, rotation still never repeats until the group is played), the check-in/free-text flows, "Next" on the end screen, any random/fallback pick, and the owner game menu (show only the 30). Keep every other game's code (switched off, reversible by editing the list). Never change approved bursts or mechanics.\n2. CRACK/STOMP: src/eos/25_eos_game_tools.jsx is UNFINISHED; 00_arcade.jsx ~L18691/18694 delegates CRACK (3) and STOMP (4) to it. If 3 or 4 is in the 30, play it to the end at 390 and 1280; if the new tool version is not solid, switch that game back to its classic engine (the classic is kept as fallback). If neither is in the 30, switch both back to classic so unfinished work never ships.\n3. Verify with Playwright (dev/drive.mjs + dev/eos_drive.mjs; the framer stub is dev/node_modules/framer; build isolated with python3 build.py --dev-dir /tmp/launch30): (a) for every router emotion, type 3 different phrases and run 3 sessions: every served game is in the 30, and no repeats before the group is played; (b) play ALL 30 to the reveal with eos_drive finishGame at 390x844, then all 30 at 1280x860 (one browser at a time; re-run a timing failure once alone before calling it a failure); 0 page errors. Fix anything that fails with the smallest change.\n4. Package: cd ${ROOT}; python3 build.py (writes ThinkStillReleaseArcade_EOS_FULL.txt), then node dev/framer_single.mjs (writes ThinkStillRelease_FRAMER.txt — must print underLimit true, < 1,048,576 bytes); then run DIR=<a harness dir built from ThinkStillRelease_FRAMER.txt as comp.jsx — copy dev/index.html + dev/main.jsx, symlink dev/node_modules, bundle with esbuild main.jsx --bundle> node dev/ship_smoke.mjs 390x844 <10 of the 30 ids> to prove the single file itself plays.\n5. Add a short "Launch 30" section at the top of ${DOCS}/SHIP_NOW_NOTES.md (which 30, how to re-enable others: edit EOS_LAUNCH_IDS, file size). Commit src changes, both .txt files, docs. ${GIT}\nBudget: <= 150 tool calls; progress notes in ${DOCS}/eos_status/launch30.progress.md every ~20 calls (read it first if it exists).\nReturn: the choke points changed, CRACK/STOMP decision, verification table (id | name | 390 | 1280), emotion-routing results, final file size, commits.`, { label: 'build:launch30', phase: 'Build' })
if (!build) throw new Error('builder returned nothing (usage limit / restart) - resume later')
return { ids: pick.ids, summary: pick.summary, build: String(build).slice(0, 6000) }
