export const meta = {
  name: 'thinkstill-ship-v1',
  description: 'Shippable v1 .txt: finish every remaining founder fix (arrows, bubble pictures, ZAP, CRACK/STOMP/real tools, CRUSH, named games, console rules, safety, routing, finale lag) on today\'s 114 games, sweep all 114 at phone + desktop with targeted fixes, then package the single Framer .txt + release notes + preview build',
  phases: [
    { title: 'Fixes', detail: '12 fix jobs, 2 at a time, highest priority first; each verified by playing at 390 then 1280' },
    { title: 'Sweep', detail: 'all 114 games at 390x844 and 1280x860 + flows + visual founder-eye review' },
    { title: 'Repair', detail: 'targeted fixes for sweep failures (games + shared), re-run only failures' },
    { title: 'Package', detail: 'single .txt, gap statuses, release notes, hosted preview build' },
  ],
}

const ROOT = '/home/user/thinkstill-rituals/framer'
const DOCS = ROOT + '/docs'
const RST = DOCS + '/eos_status'
const DONE = new Set((args && args.done) || [])

const GIT = `Git: branch claude/jolly-hopper-ognrxj in /home/user/thinkstill-rituals. Another agent works in parallel: git add ONLY the exact paths you changed (never -A/-u/.), on index.lock wait 5 s and retry, message ends with exactly:\nCo-Authored-By: Claude Opus 5.5 <noreply@anthropic.com>\nClaude-Session: https://claude.ai/code/session_01SaGZSxDbxtpggsq88ET1Ri\nthen git push -u origin claude/jolly-hopper-ognrxj (on rejection: git pull --rebase origin claude/jolly-hopper-ognrxj, then push; retry network errors 4x with 2/4/8/16 s). No PRs, no model names anywhere.`

const CTX = `PROJECT: ThinkStill Release Console — a Framer code component (React 18 + framer-motion, ONE file) of emotional-release mini-games: src/00_arcade.jsx (110 original games, 23k lines — NEVER read whole: grep, then Read offset/limit) + src/eos/*.jsx (Emotional OS modules: 00 core, 01 burst gate, 10 readability, 12 dots, 14 mood, 16 bubble face (F8 shared picture resolver tsBubbleFaceSources + useTsBubbleFaces), 21-24 new games 111-114, 30 arrows, 40 check-in, 45 router, 46 pick (ThinkStill picks, no user menu; tests start games with window.__eos.pick.start(id) / eos_drive startGameById), 50 shift meter + reveal, 52 rewards, 55 safety, 60 fixes, 62 layout guard) + src/99_pixar.jsx.
GOAL (founder, BINDING): SHIPPABLE V1 — "today's games with everything fixed (no frozen games, arrows, ThinkStill picks, bubble pictures, your bursts clean). Subscribers can use this right away." Scope + rules: ${DOCS}/founder/FEEDBACK_LOG.md (section "V1 · SHIP SCOPE" and items F1-F8), ${DOCS}/founder/GAP_AUDIT.md (§3 P0/P1 rows, §5 plan, "Founder decisions" C2-C17 — binding), rows in ${DOCS}/founder/gap_rows.json (key "rows"; grep the row id), ${DOCS}/CREATIVE_STANDARDS.md founder rules. NOT in v1: from-scratch redesigns, per-game unique climaxes, src/pilot/ (never touch it).
HARD RULES: approved dopamine bursts stay exactly as in baseline git 485500c (RewardSurgeBurst / wrappedDone / .tsRewardSurge.mega — the 01_eos_burst.jsx gate keeps EOS layers off them; lag/trigger-timing fixes only, never their look); never remove features (progress, sound, navigation, arrows, the user's own words/pictures, animations, finales); F8 bubble rules everywhere (default character picture or uploads, true circle, full image visible, user text BELOW the picture INSIDE the same object, no black masks/boxes, faces negative -> positive with progress); tools look REAL (metal, shading, weight, recoil, sound); phone 390x844 first, desktop 1280x860 second; a real human must be able to finish every game (if the auto-player needs a trick, make the real gesture easier).
SHARED-FILE DISCIPLINE (another agent edits in parallel): change src files ONLY with the Edit tool (small exact replacements) — never Write/overwrite or reformat src/00_arcade.jsx or any shared file, never git checkout/restore/stash/reset files, never revert hunks you did not write. Build ONLY isolated: python3 build.py --dev-dir /tmp/v1_<yourkey> (all modules; never plain "python3 build.py" — the deliverable .txt is rebuilt only by the package step). Before each commit run that isolated build (it must compile) and commit only your src paths + your own docs files.
TESTING: Playwright via dev/drive.mjs launch({dir:'/tmp/v1_<yourkey>', width, height}) and dev/eos_drive.mjs (startGameById, finishGame, readProgress, runCheckin, arrow helpers); probes dev/f6_probe.mjs (arrows per stage), dev/f8_probe.mjs (bubble faces/uploads), dev/f2_probe.mjs (overlap/elementFromPoint), dev/pic_probe.mjs (F10 BUBBLE FIT: pictures + text inside every bubble and easy to read — see FEEDBACK_LOG F10 for the pass rules). Tile screenshots with python3 dev/contact_sheet.py OUT.png <pngs> --cols 4 and Read the SHEET (never PNGs one by one). Headless Chromium has no GPU and no audio: sound evidence is scheduling logs only — never claim it was heard. Ignore "agent-proxy connect_rejected" noise. CPU: this machine has 4 cores shared with one other agent — run at most ONE Playwright browser at a time (no parallel shards); re-run any timing failure once before calling it a failure. The container can restart without warning: commit your src work as soon as each fix is verified (not only at the end) and keep your progress file current.
REPORTING: write your results table (row/item | cause | fix | 390 result | 1280 result | commit) to ${DOCS}/founder/v1_fix_<yourkey>.md (do NOT edit gap_rows.json — the package step merges); for a founder item (F4/F5/F6/F8) also set its status line in FEEDBACK_LOG.md to FIXED (<commit>) with a one-line verification (Edit tool, only your item's line). Budget: <= 100 tool calls, <= 12 image views; progress notes to ${RST}/v1_<yourkey>.progress.md every ~20 calls and READ IT FIRST if it exists (you may be resuming after a restart).`

const must = async (p, o) => { const r = await agent(p, o); if (r == null) throw new Error(`${o.label} returned nothing (usage limit / restart) - resume later`); return r }
const mark = (step, text) => agent(`Write the text between the markers EXACTLY to ${RST}/v1_${step}.done.md (overwrite), then git add that one file, commit "Ship v1: ${step} done" and push. ${GIT}\n<<<BEGIN>>>\n${String(text).slice(0, 7000)}\n<<<END>>>`, { label: `mark:${step}`, model: 'haiku', effort: 'low' })

// ---------------------------------------------------------------- FIX JOBS (priority order; chains run in order)
const JOBS = [
  { key: 'arrows', text: `FOUNDER ITEM F6 (guide arrows at every stage, every game, both sizes) — FINISH IT. The code fixes are committed (4284671: no auto-hide for returning players, re-show after 2.2 s idle; dev/f6_probe.mjs + eos_drive arrowCheck). Read ${RST}/v2_f6.progress.md first (state + NEXT list): run the 1280 sweep and the 390 full re-sweep on the current code, the re-show timing test, 109 CLEANSE arrow at 0%, finale plays; fix anything missing in src/eos/30_eos_arrows.jsx (EOS_GESTURES / targets) — shared, not per-game hacks; tool-first and multi-stage games must point at the tool first, then the objects. Gap row P8.3-a. Mark F6 FIXED with the sweep numbers.` },
  { key: 'bubbles-shared', text: `FOUNDER ITEM F8 + GAP plan batch 2 — ONE shared bubble standard (read F8 in FEEDBACK_LOG incl. its "Progress"/"Still open" notes, and GAP_AUDIT §3.2 rows 1-6). Implement in shared code (00_arcade.jsx L13/L14/L28 bubble CSS, GLOBAL_BUBBLE_STANDARDIZE_CSS, expandUploadImageSlots, src/eos/16_eos_bubble_face.jsx, 10_eos_readability word floor): picture in about the top 60% of the circle and the user's text block BELOW it INSIDE the circle (>= 15 px; the bubble grows instead of the text shrinking; no letters outside the circle); aspect-ratio 1 true circles (squash only as a transient); 'contain' framing with no scale-ups / no clip-path crop (whole image visible, >= 48 px picture on a phone); NO dark fills behind picture or text anywhere (soft text glow instead) plus a static lint in build.py with a reviewed whitelist so dark masks never come back; round-robin upload fill (src[k % n]: ABABAB, ABCABC, ABCDAB, ABCDEA) for every engine; the upload popup anchored right above the + button, closing on composer focus and on the 6th image, with "MAX 6" feedback and no visible internal label. Rows: P5.1-a, P5.1-c, P5.2-a/c/d, P5.4-b/c, P5.5-a/b/d/e/f, P5.6-a, P3.1-j, P14-a, P6.3-b, P6.5-a and the P6.1-*/P6.2-a popup rows. Mechanics and bursts must look unchanged. Verify with dev/f8_probe.mjs on 20 representative bubble games at 390 then 1280 (before/after sheets saved to ${DOCS}/founder/v1_bubbles_*.png).` },
  { key: 'bubbles-games', after: 'bubbles-shared', text: `FOUNDER ITEM F8 — FINISH per game on top of the shared standard just committed (see ${DOCS}/founder/v1_fix_bubbles-shared.md). Run dev/f8_probe.mjs over ALL 114 games at 390x844 AND 1280x860 with no upload; then 1, 3 and 6 uploads + upload-then-remove on 12 sampled games (1, 3, 6, 23, 41, 94, 100, 103, 105, 109, 110, 111). Fix every leftover: games still showing words without a picture (last known: 18 BURN, 38 DRAWER, 49 UNZIP, 111 BIG SIGH), POP and ZAP faces painting as empty rings at 1280, text printed over faces (86, 87, 88, 100), 100 HOT POTATO text below the image + no black mask (P13.19-g/j — founder rows override the old skip list), 93 SPACE MAKER circles (P13.11-b), 87 KEEP/DROP picture changes with the choice (P13.8-b), C12 (>= 5 bubbles except one-object-at-a-time games per the report's list). ALSO founder F10 BUBBLE FIT (FEEDBACK_LOG F10): run dev/pic_probe.mjs over ALL 114 games at 390x844 and 1280x860, no upload and --uploads 6, phases start,mid,late; fix every flag (pictures: cut/zoomed, distorted, < 48 px, < 45% of the bubble, shrunk, off-centre; text: outside the bubble shape, truncated, < 15 px, word split, > 3 lines, over the picture, contrast < 3.5) in the shared standard first, then per game; look at the crop sheets. Report counts before -> after per check and mark F8 and F10 FIXED (or list exactly what remains).` },
  { key: 'zap', text: `FOUNDER ITEM F4 — ZAP (id 6). Read F4 in FEEDBACK_LOG (the founder's words) + gap row P13.26-c. Make the zapper look and act like a REAL zapper (a handheld electric zapper/prod with metal prongs, coil glow, charge-up hum, crackling arcs, a visible bolt from the source to the target bubble, impact flash, recoil), add the ANGRY helper bubble character that eagerly helps power/aim the zap (reacts, cheers), and each zapped negative bubble's face changes from negative to a positive/relieved reaction; the bubbles carry the F8 picture with the user's text below inside; arrows point to the zapper first, then to the targets; no dark masks; the approved burst stays unchanged after the finish. Play to the end at 390 then 1280 with screenshots of the zapper, a zap, the reaction change and the finish.` },
  { key: 'tools-crack-stomp', text: `FOUNDER ITEM F5 — CRACK (id 3) + the STOMP boot (gap rows P13.26-b, P13.26-a; founder: "the stomping boot should look like a boot when the user activates it ... all tools should feel real"). CRACK: pressing the tool button produces a REAL spanner/wrench (metal, shading, weight) the user wields; each hit visibly cracks the bubble (crack lines that grow per hit, shards, impact recoil, metallic clank cue, the character inside reacts), the shell finally shatters; STOMP: the activated tool is a convincing boot (sole tread, laces, shading, weight) that stomps with anticipation, impact squash and dust. Keep mechanics, progress and the approved bursts; F8 pictures + text below inside; arrows to the tool first, then the bubbles. Play both to the end at 390 then 1280 with screenshots.` },
  { key: 'crush', text: `GAP row P13.3-a — CRUSH (id 2, the ORIGINAL game in 00_arcade.jsx, not the pilot): the object must visibly deform with each press (>= 3 growing states: dent, squash, crumple, collapse) with real press/impact feel (anticipation, squash, recoil, debris), the character reacting; keep the mechanic, progress, sound and the approved burst; F8 pictures + text below inside; no dark masks. Play to the end at 390 then 1280 with screenshots of each deformation state.` },
  { key: 'tools-audit', after: 'tools-crack-stomp', text: `FOUNDER RULE "all tools should feel real". Audit every original game that gives the player a tool or device (grep the tool buttons / tool art: hammer, scissors, shredder, vacuum, lever, plunger, knife/laser, eraser, magnet, slingshot, broom, bin, flush, press, etc.; skip ZAP, CRACK, STOMP, CRUSH — done by other jobs). Make a table id | tool | looks real? | fix. Then upgrade the tools that look like generic shapes/emoji into convincing CSS/SVG objects (material, shading, highlight, weight, anticipation + recoil, matching cue), most-routed games first (see ${DOCS}/QUALITY_REPORT.md routing), as many as fit your budget without touching mechanics or bursts; list the rest in your report for later.` },
  { key: 'games-a', text: `NAMED GAME FIXES A (gap rows; read each row's requirement/evidence/fix/test): 23 VACUUM — one column where specified (P13.16-a), a working 'Vacuum suck' button never hidden (P13.16-d), objects visibly bend/travel to the nozzle and shrink (P13.16-e); 98 MAGIC TRAPDOOR — a real interactive door/lever that swings on its hinge with the object falling through (P13.29-a/b); 110 RAIN OUT — the washout mounts within 300 ms and runs to the end, text, uploaded images and emotional objects disappear completely (P13.4-c/d/e/f), and it no longer stalls at 1280. Keep approved bursts. Play each to the end at 390 then 1280.` },
  { key: 'games-b', text: `NAMED GAME FIXES B (gap rows + founder decisions): 15 SHRED — paper visibly pulled in and torn into strips with a tear cue (P13.17-d); 21 BIN — a satisfying throw-away that completes at V1 and V2 (P13.26-e); 94 JUGGLE — How to Play uses the founder's exact words (P13.7-d, C18 in FOUNDER_REQUIREMENTS / GAP_AUDIT); 104 VOLUME KNOB — clearly turnable with grip + ticks, >= 64 px on a phone (P13.9-a, C14); X-RAY — the label is exactly "KILL / BURN ALL" (C17); 103 SINKING PLATFORM — an "Activate tool" button that lowers the platform with down arrows (C15). Keep approved bursts. Play each to the end at 390 then 1280.` },
  { key: 'games-c', text: `NAMED GAME FIXES C + reliability: FLUSH (lever feels real and obvious), MELT vs BURN (distinct cues/looks, not the same effect), TAP OUT (correct order), SCRATCH REVEAL (real scratch marks follow the finger, coverage reveals underneath) — grep the P13 rows in gap_rows.json for each; then reliability: 109 CLEANSE ends 5/5 at V1 and 5/5 at V2 (P13.2-c), 47 UNFOLLOW and 45 MAGNETS win 5/5 on a phone with touch (P13.31-b), 34 RIVER no stall at 390; and P12.2-a every player action in these games has a matching sound cue (scheduling log). Keep approved bursts. Play each at 390 then 1280.` },
  { key: 'console', text: `SHARED CONSOLE RULES (GAP plan batch 3; prefer src/eos modules, small 00_arcade.jsx edits only where unavoidable): (1) C3 founder prompt — the MAIN first screen is the composer with exactly "What emotion are you carrying?" and the supporting line "Your thoughts are materialised to be released." (P4.1-a/b); the tap-a-feeling check-in is OFF by default and becomes an optional small chip; ThinkStill detects the emotion from the user's words (keep the how-Release-works story available). (2) C5 end screen: Next (ThinkStill picks via the F3 rotation), Again, New thought — inside the container, one tap (P9.3-a). (3) Feedback toast pinned bottom-right of the stage, light, ~1-2 s, merged chain updates, never over game elements, controls or text (P3.3-a/c/d). (4) >= 44x44 hit boxes on every control (visual size unchanged) (P3.1-c); no long instruction paragraphs (fold into the one-line guide) (P3.1-f); 0 px² overlap of containers over controls (P3.1-e, re-run dev/f2_probe.mjs). (5) Sound toggle aria-pressed and covering all audio; one AudioContext; audio stops on game switch; verify the Reset shared-music path with a seeded __ts_reset_shared_media_v1 key (scheduling evidence). (6) Share card never exposes the user's private words or uploaded pictures without an explicit opt-in. Verify every item at 390 then 1280 with screenshots.` },
  { key: 'safety-routing', text: `SAFETY + ROUTING. (1) P18-b: add a threat-to-others class to EosSafetyScan (00_eos_core.jsx / 55_eos_safety.jsx): verb of harm + a person, role or name in any order ("I want to hurt my boss John", "gonna kill my ex", "I'll punch Sam") -> the gentle path with neutral words; no game copy ever pairs the person with violent verbs; self-harm handling unchanged; no false positives on ordinary release phrases ("kill this stress", "crush my deadline", "burn the anxiety") — add node unit tests. (2) P9.1-f / P13.31-c / P8.3-i: no game with a broken ending is ever served: the router and the F3 no-repeat rotation read one pass list (e.g. EOS_SHIP_BROKEN = ids that failed the latest phone or desktop sweep, initially from ${RST}/v2_unstick*.done.md and the latest sweep data) with a per-width exclusion, so the final sweep can update one constant; the rotation still never repeats until the group is played. Verify with runCheckin/composer flows at 390 and unit tests.` },
  { key: 'finale-lag', text: `FINALE LAG (lag fixes only — the founder allows these; the burst's look and choreography stay byte-identical to 485500c): P11.1-d the finale starts <= 300 ms after the last input / progress 100 (today the burst mounts 0.5-5.5 s later on some games: shorten only dead waiting, never remove a game's own outro animation), P11.1-e/i + P12.4-c no long task > 100 ms in the first 1.5 s of the burst, frame p95 stable (EOS rAF loops paused by 01_eos_burst.jsx; check for other per-frame work). Measure on 15 games (1, 2, 3, 6, 15, 18, 23, 41, 47, 94, 100, 103, 109, 110, 111) at 390 then 1280 with rAF frame times + longtask observer, before vs after; frozen-frame compare at mega +0.6 s vs baseline to prove the burst look is unchanged.` },
]

const runJob = async (j) => {
  if (DONE.has(j.key)) return { key: j.key, cached: true }
  const r = await must(`${CTX}\n\nJOB "${j.key}" (your key for /tmp/v1_${j.key}, ${RST}/v1_${j.key}.progress.md and ${DOCS}/founder/v1_fix_${j.key}.md).\n${j.text}\nCommit. ${GIT}\nReturn: a table item | cause | fix | 390 | 1280 | commit, then anything left open.`, { label: `fix:${j.key}`, phase: 'Fixes' })
  await mark(j.key, r)
  return { key: j.key, report: String(r).slice(0, 2500) }
}
// chains: a job with "after" runs right after its parent inside the same pipeline item
const roots = JOBS.filter(j => !j.after)
const kids = (k) => JOBS.filter(j => j.after === k)
phase('Fixes')
const fixed = await pipeline(roots, async (j) => {
  const out = [await runJob(j)]
  for (const c of kids(j.key)) out.push(await runJob(c))
  return out
})
const flat = fixed.filter(Boolean).flat()
if (flat.length < JOBS.length) throw new Error(`only ${flat.length}/${JOBS.length} fix jobs finished - resume later`)

// ---------------------------------------------------------------- SWEEP + REPAIR
const FAILS = { type: 'object', properties: { pass: { type: 'number' }, fail: { type: 'number' }, failing_games: { type: 'array', items: { type: 'number' } }, failures: { type: 'array', items: { type: 'object', properties: { what: { type: 'string' }, game: { type: 'number' }, size: { type: 'string' }, area: { type: 'string', enum: ['game', 'shared', 'flow'] }, evidence: { type: 'string' }, hint: { type: 'string' } }, required: ['what', 'area', 'evidence'] } } }, required: ['pass', 'fail', 'failing_games', 'failures'] }
const SWEEP = (round, size, only) => `${CTX}\n\nSHIP SWEEP round ${round} at ${size} (your key: sweep_r${round}_${size}). python3 build.py --dev-dir /tmp/v1_sweep_r${round}_${size}. Write ONE unattended node sweep (reuse dev/eos_drive.mjs + the probes) over ${only || 'ALL 114 games (1-110 + 111-114)'} at ${size}: start each by id, play to the reveal with finishGame (75 s cap), recording: finished/stuck, max progress, progress ever decreasing, page errors; arrow visible at start and at each new stage on the real target (f6 probe); OVERLAP probe at start, mid-play and pre-finale (f2: elementFromPoint at every control and word object is itself/descendant); F8 faces (f8 probe, no upload: no empty emotional object, circle, text below inside, no dark fill); F10 BUBBLE FIT (dev/pic_probe.mjs, no upload AND --uploads 6, phases start,mid,late: 0 picture or text flags); 0 text nodes over the burst core from mega mount to +1.8 s; finale start delay (progress 100 -> mega mount). Save a START + MID + FINISH screenshot per game (contact sheets of 20) and LOOK at the sheets of failing games. ${size === '390x844' ? 'Then the FLOWS at 390x844: composer prompt text exact -> type a thought -> ThinkStill picks a game (no user menu) -> finish -> shift meter -> Next / Again / New thought (Next never repeats a game until the group is played: 3 sessions); optional check-in chip; safety: "I want to hurt my boss John" takes the gentle path, a self-harm phrase shows the safety card without blocking play; uploads 0/1/3/6 + remove on 1, 41, 109; sound toggle aria-pressed; mic and + present.' : ''} Write ${DOCS}/v1_sweep_r${round}_${size}.json. Do NOT edit src files. Return counts + every failure (area game/shared/flow) with evidence and a cause hint.`

phase('Sweep')
let failing = null
let lastSweep = []
for (let round = 1; round <= 3; round++) {
  if (DONE.has(`sweep-r${round}-clean`)) { failing = []; break }
  phase('Sweep')
  const only = failing && failing.length ? `ONLY these previously failing games: ${failing.join(', ')}` : null
  const thunks = [
    () => must(SWEEP(round, '390x844', only), { label: `sweep:r${round}:390`, phase: 'Sweep', schema: FAILS }),
    () => must(SWEEP(round, '1280x860', only), { label: `sweep:r${round}:1280`, phase: 'Sweep', schema: FAILS }),
  ]
  if (round === 1) thunks.push(() => must(`${CTX}\n\nFOUNDER'S-EYE VISUAL REVIEW (key: eye). Build python3 build.py --dev-dir /tmp/v1_eye. At 390x844 capture START, MID (~50%) and FINISH-1s frames of ALL 114 games (eos_drive startGameById + scripted play / finishGame), tile them 20 per sheet and LOOK at every sheet (up to 20 image views allowed for this job). As the founder would on a phone: empty bubbles, black masks/dark boxes, squashed circles, pictures zoomed in / cut off / too small for their bubble, text outside circles, cut by the bubble edge, too small or hard to read, or over faces, overlapping containers hiding controls, missing arrows, fake-looking tools, cut-off characters, unreadable text (< 15 px), anything broken or ugly. Do NOT edit src. Return every issue (area game/shared) with game id + evidence (sheet + tile).`, { label: 'sweep:eye', phase: 'Sweep', schema: FAILS }))
  const reps = (await parallel(thunks)).filter(Boolean)
  if (reps.length < thunks.length) throw new Error(`sweep r${round} incomplete - resume later`)
  lastSweep = reps
  const all = reps.flatMap(r => r.failures)
  failing = [...new Set(reps.flatMap(r => r.failing_games).concat(all.filter(f => typeof f.game === 'number').map(f => f.game)))].sort((a, b) => a - b)
  log(`Sweep r${round}: ${reps.map(r => `${r.pass} pass / ${r.fail} fail`).join(' | ')}; failures ${all.length}; failing games ${failing.join(', ') || 'none'}`)
  if (!all.length) { await mark(`sweep-r${round}-clean`, `Sweep round ${round} clean at 390 and 1280.`); failing = []; break }
  if (round === 3) break
  phase('Repair')
  const gameF = all.filter(f => f.area === 'game')
  const sharedF = all.filter(f => f.area !== 'game')
  const fixThunks = []
  if (gameF.length) fixThunks.push(() => must(`${CTX}\n\nREPAIR round ${round} — GAME failures (key: repair_r${round}_games). Fix each with the smallest behaviour-preserving change in the game's own code, rebuild isolated, and re-run ONLY the failing game at the failing size to prove it passes. A game you cannot fix reliably must be added to the routing exclusion list (EOS_SHIP_BROKEN or equivalent from the safety-routing job) for that width so it is never served broken — say so. Commit. ${GIT}\nFailures:\n${JSON.stringify(gameF, null, 1).slice(0, 14000)}`, { label: `repair:r${round}:games`, phase: 'Repair' }))
  if (sharedF.length) fixThunks.push(() => must(`${CTX}\n\nREPAIR round ${round} — SHARED + FLOW failures (key: repair_r${round}_shared). Fix each in the owning shared code (prefer src/eos), rebuild isolated, re-run only the failing checks at the failing size. Commit. ${GIT}\nFailures:\n${JSON.stringify(sharedF, null, 1).slice(0, 14000)}`, { label: `repair:r${round}:shared`, phase: 'Repair' }))
  const fx = (await parallel(fixThunks)).filter(Boolean)
  if (fx.length < fixThunks.length) throw new Error(`repair r${round} incomplete - resume later`)
  await mark(`repair-r${round}`, fx.join('\n\n'))
}

// ---------------------------------------------------------------- PACKAGE
phase('Package')
let pkg = 'already done'
if (!DONE.has('package')) {
  pkg = await must(`${CTX}\n\nPACKAGE SHIPPABLE V1 (key: package; you are the ONLY agent now, so plain builds are allowed). cd ${ROOT}; python3 build.py -> ThinkStillReleaseArcade_EOS_FULL.txt; confirm it is ONE self-contained file (imports only at the top, exactly one export default, all original property controls + new ones, compiles with esbuild, no src/pilot code, no dev-only hooks exposed to users except the documented owner/test hooks). Final smoke at 390 and 1280: composer prompt -> type a panic thought -> ThinkStill picks -> play to the reveal -> shift meter -> Next; POP; UNFOLLOW; ZAP; CRACK; zero page errors. Merge every ${DOCS}/founder/v1_fix_*.md into ${DOCS}/founder/gap_rows.json statuses (FIXED + commit, or still PARTIAL with the reason) and append a "Fixed in v1" section to GAP_AUDIT.md. Write ${DOCS}/RELEASE_NOTES_v1.md for the founder (plain language, short): how to paste the .txt into a Framer code component, what is new, what was fixed (frozen games, arrows, ThinkStill picks, bubble pictures, clean bursts, ZAP, CRACK, STOMP, tools, named games, prompt, end screen, safety), property controls, KNOWN ISSUES honestly (remaining sweep failures: ${JSON.stringify(failing)} and any game excluded from routing; real-device touch/performance and audible sound still to be confirmed on the founder's phone; per-game unique climaxes and the from-scratch redesign are not in v1). Then build the hosted preview: python3 dev/preview_build.py /tmp/v1_preview and in /tmp/v1_preview/app.js replace width:"100vw",height:"100vh" with width:"100%",height:"100%"; check it loads (serve with python3 -m http.server and open with ${ROOT}/preview/index.html copied next to it). Commit the .txt, gap_rows.json, GAP_AUDIT.md and RELEASE_NOTES_v1.md. ${GIT} Return: .txt path + size + line count, compile result, smoke results, known issues, preview folder.`, { label: 'package', phase: 'Package' })
  await mark('package', pkg)
}
return { jobs: flat.map(f => f.key), failing, sweeps: lastSweep.map(r => ({ pass: r.pass, fail: r.fail, failing: r.failing_games })), pkg: String(pkg).slice(0, 4000) }
