/* Room core tests: privacy until reveal, companions, dedupe, rejoin, host rules, spectators. */
import { RoomHub } from '../src/room/hub';
import { REGISTRY } from '../src/rituals/registry';
declare const process: any;
let fails = 0;
const ok = (c: any, msg: string) => { if (!c) { fails++; console.log('FAIL', msg); } else console.log('ok  ', msg); };
const hub = new RoomHub(REGISTRY, 'ABCDE', 'group-think-glitch');
const inbox: Record<string, any[]> = { a: [], b: [] };
const A: any = { send: (m: any) => inbox.a.push(m) }, B: any = { send: (m: any) => inbox.b.push(m) };
hub.open(A); hub.open(B);
hub.message(A, JSON.stringify({ t: 'hello', room: 'ABCDE', name: 'Ana', avatar: 'patch' }));
hub.message(B, JSON.stringify({ t: 'hello', room: 'ABCDE', name: 'Ben', avatar: 'rush' }));
const last = (k: string) => [...inbox[k]].reverse().find(m => m.t === 'state' || m.t === 'welcome').view;
const tokB = inbox.b.find(m => m.t === 'welcome').token;
ok(last('a').players.length === 2 && last('a').hostPid === A.pid, 'two humans, first is host');
hub.message(B, JSON.stringify({ t: 'act', id: 'x1', kind: 'start' }));
ok(last('a').phase === 'lobby', 'non-host cannot start');
hub.message(A, JSON.stringify({ t: 'act', id: 'c1', kind: 'add_companion', data: { avatar: 'glitch' } }));
hub.message(A, JSON.stringify({ t: 'act', id: 's1', kind: 'start', data: { seed: 42 } }));
let v = last('a');
ok(v.phase === 'play' && v.players.length === 3, 'started with a companion');
ok(v.sealed['c-glitch'] === true, 'companion sealed by its rules');
ok(!('mine' in v) || v.mine === undefined, 'nothing sealed yet for Ana');
const camA = v.pub.cams[A.pid];
const spots = require('../src/rituals/group-think-glitch/content').hotspotsFor(camA).map((h: any) => h.id);
hub.message(A, JSON.stringify({ t: 'act', id: 'p1', kind: 'seal', data: { pins: spots.slice(0, 2), suspect: 'cat', sure: 2, path: [1, 0.5, 0.5] } }));
hub.message(A, JSON.stringify({ t: 'act', id: 'p1', kind: 'seal', data: { pins: spots.slice(0, 1), suspect: 'rush', sure: 0 } }));
v = last('b');
ok(v.sealed[A.pid] === true && v.revealed === null, 'Ben sees that Ana sealed, not what');
ok(JSON.stringify(v).indexOf('"suspect"') === -1, 'no sealed payload anywhere in Ben\'s view');
ok(last('a').mine && last('a').mine.suspect === 'cat', 'Ana sees her own sealed verdict; duplicate ignored');
// Ben drops and rejoins with his token, then seals
hub.close(B);
ok(last('a').players.find((p: any) => p.pid === B.pid).connected === false, 'disconnect is visible');
const B2: any = { send: (m: any) => inbox.b.push(m) }; hub.open(B2);
hub.message(B2, JSON.stringify({ t: 'hello', room: 'ABCDE', name: 'Ben', avatar: 'rush', token: tokB }));
ok(B2.pid === B.pid, 'rejoin restores the same seat');
const camB = last('b').pub.cams[B2.pid];
const spotsB = require('../src/rituals/group-think-glitch/content').hotspotsFor(camB).map((h: any) => h.id);
hub.message(B2, JSON.stringify({ t: 'act', id: 'q1', kind: 'seal', data: { pins: ['nope'], suspect: 'cat' } }));
ok(last('b').sealed[B2.pid] !== true, 'invalid evidence rejected');
hub.message(B2, JSON.stringify({ t: 'act', id: 'q2', kind: 'seal', data: { pins: spotsB.slice(0, 3), suspect: 'rush', sure: 1 } }));
v = last('a');
ok(v.phase === 'reveal' && v.revealed[B2.pid].suspect === 'rush' && v.revealed[A.pid].suspect === 'cat', 'everyone sealed → reveal with all verdicts');
// a late joiner is a spectator
const C: any = { send: () => {} }; hub.open(C);
hub.message(C, JSON.stringify({ t: 'hello', room: 'ABCDE', name: 'Cat', avatar: 'sync' }));
ok(last('a').players.find((p: any) => p.pid === C.pid).spectator === true, 'late joiner watches as a spectator');
hub.message(A, JSON.stringify({ t: 'act', id: 'r1', kind: 'replay' }));
ok(last('a').phase === 'lobby' && last('a').players.find((p: any) => p.pid === C.pid).spectator === false, 'replay seats the spectator');
console.log(fails ? `${fails} FAILED` : 'all room tests passed');
process.exit(fails ? 1 : 0);
